package com.cosmeticos.payment.cielo.model;

import lombok.Getter;

/**
 * Retentativas com 4 significa 4 tentativas em 16 dias
 * Retentativas com 04 significa que, a partir do dia seguinte, 4 tentativas em 16 dias.
 * Documentacao Cielo: https://developercielo.github.io/manual/cielo-ecommerce#c%C3%B3digos-de-retorno-das-vendas
 */
@Getter
public enum CieloOrderReturnCode {
    SUCESSO_00("00", "Transacao autorizada com sucesso.", "Transacao autorizada com sucesso.", "Transacao autorizada com sucesso.", 0),
    SUCESSO_000("000", "Transacao autorizada com sucesso.", "Transacao autorizada com sucesso.", "Transacao autorizada com sucesso.", 0),
    FALHA_01("01", "Transacao nao autorizada. Transacao referida.", "Transacao nao autorizada. Referida (suspeita de fraude) pelo banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_02("02", "Transacao nao autorizada. Transacao referida.", "Transacao nao autorizada. Referida (suspeita de fraude) pelo banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_03("03", "Transacao nao permitida. Erro no cadastramento do código do estabelecimento no arquivo de configuracao do TEF", "Transacao nao permitida. Estabelecimento invalido. Entre com contato com a Cielo.", "Nao foi possível processar a transacao. Entre com contato com a Loja Virtual.", 0),
    FALHA_04("04", "Transacao nao autorizada. Cartao bloqueado pelo banco emissor.", "Transacao nao autorizada. Cartao bloqueado pelo banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_05("05", "Transacao nao autorizada. Cartao inadimplente (Do not honor).", "Transacao nao autorizada. Nao foi possível processar a transacao. Questao relacionada a seguranca, inadimplencia ou limite do portador.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_06("06", "Transacao nao autorizada. Cartao cancelado.", "Transacao nao autorizada. Nao foi possível processar a transacao. Cartao cancelado permanentemente pelo banco emissor.", "Nao foi possível processar a transacao. Entre em contato com seu banco emissor.", 0),
    FALHA_07("07", "Transacao negada. Reter cartao condicao especial", "Transacao nao autorizada por regras do banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor", 0),
    FALHA_08("08", "Transacao nao autorizada. Código de seguranca invalido.", "Transacao nao autorizada. Código de seguranca invalido. Oriente o portador a corrigir os dados e tentar novamente.", "Transacao nao autorizada. Dados incorretos. Reveja os dados e informe novamente.", 0),
    FALHA_11("11", "Transacao autorizada com sucesso para cartao emitido no exterior", "Transacao autorizada com sucesso.", "Transacao autorizada com sucesso.", 0),
    FALHA_12("12", "Transacao invalida, erro no cartao.", "Nao foi possível processar a transacao. Solicite ao portador que verifique os dados do cartao e tente novamente.", "Nao foi possível processar a transacao. reveja os dados informados e tente novamente. Se o erro persistir, entre em contato com seu banco emissor.", 0),
    FALHA_13("13", "Transacao nao permitida. Valor da transacao Invalido.", "Transacao nao permitida. Valor invalido. Solicite ao portador que reveja os dados e novamente. Se o erro persistir, entre em contato com a Cielo.", "Transacao nao autorizada. Valor invalido. Refazer a transacao confirmando os dados informados. Persistindo o erro, entrar em contato com a loja virtual.", 0),
    FALHA_14("14", "Transacao nao autorizada. Cartao Invalido", "Transacao nao autorizada. Cartao invalido. Pode ser bloqueio do cartao no banco emissor, dados incorretos ou tentativas de testes de cartao. Use o Algoritmo de Lhum (Mod 10) para evitar transacões nao autorizadas por esse motivo. Consulte www.cielo.com.br/desenvolvedores para implantar o Algoritmo de Lhum.", "Nao foi possível processar a transacao. reveja os dados informados e tente novamente. Se o erro persistir, entre em contato com seu banco emissor.", 0),
    FALHA_15("15", "Banco emissor indisponível ou inexistente.", "Transacao nao autorizada. Banco emissor indisponível.", "Nao foi possível processar a transacao. Entre em contato com seu banco emissor.", 0),
    FALHA_19("19", "Refaca a transacao ou tente novamente mais tarde.", "Nao foi possível processar a transacao. Refaca a transacao ou tente novamente mais tarde. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar a transacao. Refaca a transacao ou tente novamente mais tarde. Se o erro persistir entre em contato com a loja virtual.", 4),
    FALHA_21("21", "Cancelamento nao efetuado. Transacao nao localizada.", "Nao foi possível processar o cancelamento. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar o cancelamento. Tente novamente mais tarde. Persistindo o erro, entrar em contato com a loja virtual.", 0),
    FALHA_22("22", "Parcelamento invalido. Número de parcelas invalidas.", "Nao foi possível processar a transacao. Número de parcelas invalidas. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar a transacao. Valor invalido. Refazer a transacao confirmando os dados informados. Persistindo o erro, entrar em contato com a loja virtual.", 0),
    FALHA_23("23", "Transacao nao autorizada. Valor da prestacao invalido.", "Nao foi possível processar a transacao. Valor da prestacao invalido. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar a transacao. Valor da prestacao invalido. Refazer a transacao confirmando os dados informados. Persistindo o erro, entrar em contato com a loja virtual.", 0),
    FALHA_24("24", "Quantidade de parcelas invalido.", "Nao foi possível processar a transacao. Quantidade de parcelas invalido. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar a transacao. Quantidade de parcelas invalido. Refazer a transacao confirmando os dados informados. Persistindo o erro, entrar em contato com a loja virtual.", 0),
    FALHA_25("25", "Pedido de autorizacao nao enviou número do cartao", "Nao foi possível processar a transacao. Solicitacao de autorizacao nao enviou o número do cartao. Se o erro persistir, verifique a comunicacao entre loja virtual e Cielo.", "Nao foi possível processar a transacao. reveja os dados informados e tente novamente. Persistindo o erro, entrar em contato com a loja virtual.", 4),
    FALHA_28("28", "Arquivo temporariamente indisponível.", "Nao foi possível processar a transacao. Arquivo temporariamente indisponível. Reveja a comunicacao entre Loja Virtual e Cielo. Se o erro persistir, entre em contato com a Cielo.", "Nao foi possível processar a transacao. Entre com contato com a Loja Virtual.", 4),
    FALHA_30("30", "Transacao nao autorizada. Decline Message", "Nao foi possível processar a transacao. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir verifique a comunicacao com a Cielo esta sendo feita corretamente", "Nao foi possível processar a transacao. Reveja os dados e tente novamente. Se o erro persistir, entre em contato com a loja", 0),
    FALHA_39("39", "Transacao nao autorizada. Erro no banco emissor.", "Transacao nao autorizada. Erro no banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_41("41", "Transacao nao autorizada. Cartao bloqueado por perda.", "Transacao nao autorizada. Cartao bloqueado por perda.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_43("43", "Transacao nao autorizada. Cartao bloqueado por roubo.", "Transacao nao autorizada. Cartao bloqueado por roubo.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_51("51", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 04),
    FALHA_52("52", "Cartao com dígito de controle invalido.", "Nao foi possível processar a transacao. Cartao com dígito de controle invalido.", "Transacao nao autorizada. Reveja os dados informados e tente novamente.", 0),
    FALHA_53("53", "Transacao nao permitida. Cartao poupanca invalido", "Transacao nao permitida. Cartao poupanca invalido.", "Nao foi possível processar a transacao. Entre em contato com seu banco emissor.", 0),
    FALHA_54("54", "Transacao nao autorizada. Cartao vencido", "Transacao nao autorizada. Cartao vencido.", "Transacao nao autorizada. Refazer a transacao confirmando os dados.", 0),
    FALHA_55("55", "Transacao nao autorizada. Senha invalida", "Transacao nao autorizada. Senha invalida.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_57("57", "Transacao nao permitida para o cartao", "Transacao nao autorizada. Transacao nao permitida para o cartao.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_58("58", "Transacao nao permitida. Opcao de pagamento invalida.", "Transacao nao permitida. Opcao de pagamento invalida. Reveja se a opcao de pagamento escolhida esta habilitada no cadastro", "Transacao nao autorizada. Entre em contato com sua loja virtual.", 0),
    FALHA_59("59", "Transacao nao autorizada. Suspeita de fraude.", "Transacao nao autorizada. Suspeita de fraude.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_60("60", "Transacao nao autorizada.", "Transacao nao autorizada. Tente novamente. Se o erro persistir o portador deve entrar em contato com o banco emissor.", "Nao foi possível processar a transacao. Tente novamente mais tarde. Se o erro persistir, entre em contato com seu banco emissor.", 4),
    FALHA_61("61", "Banco emissor indisponível.", "Transacao nao autorizada. Banco emissor indisponível.", "Transacao nao autorizada. Tente novamente. Se o erro persistir, entre em contato com seu banco emissor.", 4),
    FALHA_62("62", "Transacao nao autorizada. Cartao restrito para uso doméstico", "Transacao nao autorizada. Cartao restrito para uso doméstico.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 04),
    FALHA_63("63", "Transacao nao autorizada. Violacao de seguranca", "Transacao nao autorizada. Violacao de seguranca.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_64("64", "Transacao nao autorizada. Valor abaixo do mínimo exigido pelo banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", "Transacao nao autorizada. Valor abaixo do mínimo exigido pelo banco emissor.", 0),
    FALHA_65("65", "Transacao nao autorizada. Excedida a quantidade de transacões para o cartao.", "Transacao nao autorizada. Excedida a quantidade de transacões para o cartao.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_67("67", "Transacao nao autorizada. Cartao bloqueado para compras hoje.", "Transacao nao autorizada. Cartao bloqueado para compras hoje. Bloqueio pode ter ocorrido por excesso de tentativas invalidas. O cartao sera desbloqueado automaticamente à meia noite.", "Transacao nao autorizada. Cartao bloqueado temporariamente. Entre em contato com seu banco emissor.", 04),
    FALHA_70("70", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 04),
    FALHA_72("72", "Cancelamento nao efetuado. Saldo disponível para cancelamento insuficiente.", "Cancelamento nao efetuado. Saldo disponível para cancelamento insuficiente. Se o erro persistir, entre em contato com a Cielo.", "Cancelamento nao efetuado. Tente novamente mais tarde. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_74("74", "Transacao nao autorizada. A senha esta vencida.", "Transacao nao autorizada. A senha esta vencida.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_75("75", "Senha bloqueada. Excedeu tentativas de cartao.", "Transacao nao autorizada.", "Sua Transacao nao pode ser processada. Entre em contato com o Emissor do seu cartao.", 0),
    FALHA_76("76", "Cancelamento nao efetuado. Banco emissor nao localizou a transacao original", "Cancelamento nao efetuado. Banco emissor nao localizou a transacao original", "Cancelamento nao efetuado. Entre em contato com a loja virtual.", 0),
    FALHA_77("77", "Cancelamento nao efetuado. Nao foi localizado a transacao original", "Cancelamento nao efetuado. Nao foi localizado a transacao original", "Cancelamento nao efetuado. Entre em contato com a loja virtual.", 0),
    FALHA_78("78", "Transacao nao autorizada. Cartao bloqueado primeiro uso.", "Transacao nao autorizada. Cartao bloqueado primeiro uso. Solicite ao portador que desbloqueie o cartao diretamente com seu banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor e solicite o desbloqueio do cartao.", 0),
    FALHA_80("80", "Transacao nao autorizada. Divergencia na data de transacao/pagamento.", "Transacao nao autorizada. Data da transacao ou data do primeiro pagamento invalida.", "Transacao nao autorizada. Refazer a transacao confirmando os dados.", 0),
    FALHA_82("82", "Transacao nao autorizada. Cartao invalido.", "Transacao nao autorizada. Cartao Invalido. Solicite ao portador que reveja os dados e tente novamente.", "Transacao nao autorizada. Refazer a transacao confirmando os dados. Se o erro persistir, entre em contato com seu banco emissor.", 0),
    FALHA_83("83", "Transacao nao autorizada. Erro no controle de senhas", "Transacao nao autorizada. Erro no controle de senhas", "Transacao nao autorizada. Refazer a transacao confirmando os dados. Se o erro persistir, entre em contato com seu banco emissor.", 0),
    FALHA_85("85", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_86("86", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_89("89", "Erro na transacao.", "Transacao nao autorizada. Erro na transacao. O portador deve tentar novamente e se o erro persistir, entrar em contato com o banco emissor.", "Transacao nao autorizada. Erro na transacao. Tente novamente e se o erro persistir, entre em contato com seu banco emissor.", 4),
    FALHA_90("90", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_91("91", "Transacao nao autorizada. Banco emissor temporariamente indisponível.", "Transacao nao autorizada. Banco emissor temporariamente indisponível.", "Transacao nao autorizada. Banco emissor temporariamente indisponível. Entre em contato com seu banco emissor.", 4),
    FALHA_92("92", "Transacao nao autorizada. Tempo de comunicacao excedido.", "Transacao nao autorizada. Tempo de comunicacao excedido.", "Transacao nao autorizada. Comunicacao temporariamente indisponível. Entre em contato com a loja virtual.", 4),
    FALHA_93("93", "Transacao nao autorizada. Violacao de regra - Possível erro no cadastro.", "Transacao nao autorizada. Violacao de regra - Possível erro no cadastro.", "Sua transacao nao pode ser processada. Entre em contato com a loja virtual.", 0),
    FALHA_96("96", "Falha no processamento.", "Nao foi possível processar a transacao. Falha no sistema da Cielo. Se o erro persistir, entre em contato com a Cielo.", "Sua Transacao nao pode ser processada, Tente novamente mais tarde. Se o erro persistir, entre em contato com a loja virtual.", 4),
    FALHA_97("97", "Valor nao permitido para essa transacao.", "Transacao nao autorizada. Valor nao permitido para essa transacao.", "Transacao nao autorizada. Valor nao permitido para essa transacao.", 0),
    FALHA_98("98", "Sistema/comunicacao indisponível.", "Transacao nao autorizada. Sistema do emissor sem comunicacao. Se for geral, verificar SITEF, GATEWAY e/ou Conectividade.", "Sua Transacao nao pode ser processada, Tente novamente mais tarde. Se o erro persistir, entre em contato com a loja virtual.", 4),
    FALHA_99("99", "Sistema/comunicacao indisponível.", "Transacao nao autorizada. Sistema do emissor sem comunicacao. Tente mais tarde. Pode ser erro no SITEF, favor verificar !", "Sua Transacao nao pode ser processada, Tente novamente mais tarde. Se o erro persistir, entre em contato com a loja virtual.", 04),
    FALHA_999("999", "Sistema/comunicacao indisponível.", "Transacao nao autorizada. Sistema do emissor sem comunicacao. Tente mais tarde. Pode ser erro no SITEF, favor verificar !", "Sua Transacao nao pode ser processada, Tente novamente mais tarde. Se o erro persistir, entre em contato com a loja virtual.", 04),
    FALHA_AA("AA", "Tempo Excedido", "Tempo excedido na comunicacao com o banco emissor. Oriente o portador a tentar novamente, se o erro persistir sera necessario que o portador contate seu banco emissor.", "Tempo excedido na sua comunicacao com o banco emissor, tente novamente mais tarde. Se o erro persistir, entre em contato com seu banco.", 4),
    FALHA_AC("AC", "Transacao nao permitida. Cartao de débito sendo usado com crédito. Use a funcao débito.", "Transacao nao permitida. Cartao de débito sendo usado com crédito. Solicite ao portador que selecione a opcao de pagamento Cartao de Débito.", "Transacao nao autorizada. Tente novamente selecionando a opcao de pagamento cartao de débito.", 0),
    FALHA_AE("AE", "Tente Mais Tarde", "Tempo excedido na comunicacao com o banco emissor. Oriente o portador a tentar novamente, se o erro persistir sera necessario que o portador contate seu banco emissor.", "Tempo excedido na sua comunicacao com o banco emissor, tente novamente mais tarde. Se o erro persistir, entre em contato com seu banco.", 4),
    FALHA_AF("AF", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_AG("AG", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_AH("AH", "Transacao nao permitida. Cartao de crédito sendo usado com débito. Use a funcao crédito.", "Transacao nao permitida. Cartao de crédito sendo usado com débito. Solicite ao portador que selecione a opcao de pagamento Cartao de Crédito.", "Transacao nao autorizada. Tente novamente selecionando a opcao de pagamento cartao de crédito.", 0),
    FALHA_AI("AI", "Transacao nao autorizada. Autenticacao nao foi realizada.", "Transacao nao autorizada. Autenticacao nao foi realizada. O portador nao concluiu a autenticacao. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir, entre em contato com a Cielo informando o BIN (6 primeiros dígitos do cartao)", "Transacao nao autorizada. Autenticacao nao foi realizada com sucesso. Tente novamente e informe corretamente os dados solicitado. Se o erro persistir, entre em contato com o lojista.", 0),
    FALHA_AJ("AJ", "Transacao nao permitida. Transacao de crédito ou débito em uma operacao que permite apenas Private Label. Tente novamente selecionando a opcao Private Label.", "Transacao nao permitida. Transacao de crédito ou débito em uma operacao que permite apenas Private Label. Solicite ao portador que tente novamente selecionando a opcao Private Label. Caso nao disponibilize a opcao Private Label verifique na Cielo se o seu estabelecimento permite essa operacao.", "Transacao nao permitida. Transacao de crédito ou débito em uma operacao que permite apenas Private Label. Tente novamente e selecione a opcao Private Label. Em caso de um novo erro entre em contato com a loja virtual.", 0),
    FALHA_AV("AV", "Transacao nao autorizada. Dados Invalidos", "Falha na validacao dos dados da transacao. Oriente o portador a rever os dados e tentar novamente.", "Falha na validacao dos dados. Reveja os dados informados e tente novamente.", 4),
    FALHA_BD("BD", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento.Solicite ao portador que digite novamente os dados do cartao, se o erro persistir pode haver um problema no terminal do lojista, nesse caso o lojista deve entrar em contato com a Cielo.", "Transacao nao permitida. Informe os dados do cartao novamente. Se o erro persistir, entre em contato com a loja virtual.", 0),
    FALHA_BL("BL", "Transacao nao autorizada. Limite diario excedido.", "Transacao nao autorizada. Limite diario excedido. Solicite ao portador que entre em contato com seu banco emissor.", "Transacao nao autorizada. Limite diario excedido. Entre em contato com seu banco emissor.", 04),
    FALHA_BM("BM", "Transacao nao autorizada. Cartao Invalido", "Transacao nao autorizada. Cartao invalido. Pode ser bloqueio do cartao no banco emissor ou dados incorretos. Tente usar o Algoritmo de Lhum (Mod 10) para evitar transacões nao autorizadas por esse motivo.", "Transacao nao autorizada. Cartao invalido. Refaca a transacao confirmando os dados informados.", 0),
    FALHA_BN("BN", "Transacao nao autorizada. Cartao ou conta bloqueado.", "Transacao nao autorizada. O cartao ou a conta do portador esta bloqueada. Solicite ao portador que entre em contato com seu banco emissor.", "Transacao nao autorizada. O cartao ou a conta do portador esta bloqueada. Entre em contato com seu banco emissor.", 0),
    FALHA_BO("BO", "Transacao nao permitida. Falha da operacao.", "Transacao nao permitida. Houve um erro no processamento. Solicite ao portador que digite novamente os dados do cartao, se o erro persistir, entre em contato com o banco emissor.", "Transacao nao permitida. Houve um erro no processamento. Digite novamente os dados do cartao, se o erro persistir, entre em contato com o banco emissor.", 4),
    FALHA_BP("BP", "Transacao nao autorizada. Conta corrente inexistente.", "Transacao nao autorizada. Nao possível processar a transacao por um erro relacionado ao cartao ou conta do portador. Solicite ao portador que entre em contato com o banco emissor.", "Transacao nao autorizada. Nao possível processar a transacao por um erro relacionado ao cartao ou conta do portador. Entre em contato com o banco emissor.", 0),
    FALHA_BV("BV", "Transacao nao autorizada. Cartao vencido", "Transacao nao autorizada. Cartao vencido.", "Transacao nao autorizada. Refazer a transacao confirmando os dados.", 0),
    FALHA_CF("CF", "Transacao nao autorizada.C79:J79 Falha na validacao dos dados.", "Transacao nao autorizada. Falha na validacao dos dados. Solicite ao portador que entre em contato com o banco emissor.", "Transacao nao autorizada. Falha na validacao dos dados. Entre em contato com o banco emissor.", 0),
    FALHA_CG("CG", "Transacao nao autorizada. Falha na validacao dos dados.", "Transacao nao autorizada. Falha na validacao dos dados. Solicite ao portador que entre em contato com o banco emissor.", "Transacao nao autorizada. Falha na validacao dos dados. Entre em contato com o banco emissor.", 0),
    FALHA_DA("DA", "Transacao nao autorizada. Falha na validacao dos dados.", "Transacao nao autorizada. Falha na validacao dos dados. Solicite ao portador que entre em contato com o banco emissor.", "Transacao nao autorizada. Falha na validacao dos dados. Entre em contato com o banco emissor.", 0),
    FALHA_DF("DF", "Transacao nao permitida. Falha no cartao ou cartao invalido.", "Transacao nao permitida. Falha no cartao ou cartao invalido. Solicite ao portador que digite novamente os dados do cartao, se o erro persistir, entre em contato com o banco", "Transacao nao permitida. Falha no cartao ou cartao invalido. Digite novamente os dados do cartao, se o erro persistir, entre em contato com o banco", 4),
    FALHA_DM("DM", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Limite excedido/sem saldo.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 04),
    FALHA_DQ("DQ", "Transacao nao autorizada. Falha na validacao dos dados.", "Transacao nao autorizada. Falha na validacao dos dados. Solicite ao portador que entre em contato com o banco emissor.", "Transacao nao autorizada. Falha na validacao dos dados. Entre em contato com o banco emissor.", 0),
    FALHA_DS("DS", "Transacao nao permitida para o cartao", "Transacao nao autorizada. Transacao nao permitida para o cartao.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_EB("EB", "Transacao nao autorizada. Limite diario excedido.", "Transacao nao autorizada. Limite diario excedido. Solicite ao portador que entre em contato com seu banco emissor.", "Transacao nao autorizada. Limite diario excedido. Entre em contato com seu banco emissor.", 04),
    FALHA_EE("EE", "Transacao nao permitida. Valor da parcela inferior ao mínimo permitido.", "Transacao nao permitida. Valor da parcela inferior ao mínimo permitido. Nao é permitido parcelas inferiores a R$ 5,00. Necessario rever calculo para parcelas.", "Transacao nao permitida. O valor da parcela esta abaixo do mínimo permitido. Entre em contato com a loja virtual.", 0),
    FALHA_EK("EK", "Transacao nao permitida para o cartao", "Transacao nao autorizada. Transacao nao permitida para o cartao.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_FA("FA", "Transacao nao autorizada.", "Transacao nao autorizada AmEx.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_FC("FC", "Transacao nao autorizada. Ligue Emissor", "Transacao nao autorizada. Oriente o portador a entrar em contato com o banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 0),
    FALHA_FD("FD", "Transacao negada. Reter cartao condicao especial", "Transacao nao autorizada _regraspor regras do banco emissor.", "Transacao nao autorizada. Entre em contato com seu banco emissor", 0),
    FALHA_FE("FE", "Transacao nao autorizada. Divergencia na data de transacao/pagamento.", "Transacao nao autorizada. Data da transacao ou data do primeiro pagamento invalida.", "Transacao nao autorizada. Refazer a transacao confirmando os dados.", 0),
    FALHA_FF("FF", "Cancelamento OK", "Transacao de cancelamento autorizada com sucesso. ATENÇÂO: Esse retorno é para casos de cancelamentos e nao para casos de autorizacões.", "Transacao de cancelamento autorizada com sucesso", 0),
    // Esste esta duplicado na documentacao da cielo. FALHA_FG("FG", "Transacao nao autorizada. Ligue AmEx.", "Transacao nao autorizada. Oriente o portador a entrar em contato com a Central de Atendimento AmEx.", "Transacao nao autorizada. Entre em contato com a Central de Atendimento AmEx no telefone 08007285090", 0),
    FALHA_FG("FG", "Ligue 08007285090", "Transacao nao autorizada. Oriente o portador a entrar em contato com a Central de Atendimento AmEx.", "Transacao nao autorizada. Entre em contato com a Central de Atendimento AmEx no telefone 08007285090", 0),
    FALHA_GA("GA", "Aguarde Contato", "Transacao nao autorizada. Referida pelo Lynx Online de forma preventiva. A Cielo entrara em contato com o lojista sobre esse caso.", "Transacao nao autorizada. Entre em contato com o lojista.", 0),
    FALHA_HJ("HJ", "Transacao nao permitida. Código da operacao invalido.", "Transacao nao permitida. Código da operacao Coban invalido.", "Transacao nao permitida. Código da operacao Coban invalido. Entre em contato com o lojista.", 0),
    FALHA_IA("IA", "Transacao nao permitida. Indicador da operacao invalido.", "Transacao nao permitida. Indicador da operacao Coban invalido.", "Transacao nao permitida. Indicador da operacao Coban invalido. Entre em contato com o lojista.", 0),
    FALHA_JB("JB", "Transacao nao permitida. Valor da operacao invalido.", "Transacao nao permitida. Valor da operacao Coban invalido.", "Transacao nao permitida. Valor da operacao Coban invalido. Entre em contato com o lojista.", 0),
    FALHA_KA("KA", "Transacao nao permitida. Falha na validacao dos dados.", "Transacao nao permitida. Houve uma falha na validacao dos dados. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir verifique a comunicacao entre loja virtual e Cielo.", "Transacao nao permitida. Houve uma falha na validacao dos dados. reveja os dados informados e tente novamente. Se o erro persistir entre em contato com a Loja Virtual.", 0),
    FALHA_KB("KB", "Transacao nao permitida. Selecionado a opcao incorrente.", "Transacao nao permitida. Selecionado a opcao incorreta. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir deve ser verificado a comunicacao entre loja virtual e Cielo.", "Transacao nao permitida. Selecionado a opcao incorreta. Tente novamente. Se o erro persistir entre em contato com a Loja Virtual.", 0),
    FALHA_KE("KE", "Transacao nao autorizada. Falha na validacao dos dados.", "Transacao nao autorizada. Falha na validacao dos dados. Opcao selecionada nao esta habilitada. Verifique as opcões disponíveis para o portador.", "Transacao nao autorizada. Falha na validacao dos dados. Opcao selecionada nao esta habilitada. Entre em contato com a loja virtual.", 0),
    FALHA_N7("N7", "Transacao nao autorizada. Código de seguranca invalido.", "Transacao nao autorizada. Código de seguranca invalido. Oriente o portador corrigir os dados e tentar novamente.", "Transacao nao autorizada. Reveja os dados e informe novamente.", 0),
    FALHA_R1("R1", "Transacao nao autorizada. Cartao inadimplente (Do not honor).", "Transacao nao autorizada. Nao foi possível processar a transacao. Questao relacionada a seguranca, inadimplencia ou limite do portador.", "Transacao nao autorizada. Entre em contato com seu banco emissor.", 4),
    FALHA_U3("U3", "Transacao nao permitida. Falha na validacao dos dados.", "Transacao nao permitida. Houve uma falha na validacao dos dados. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir verifique a comunicacao entre loja virtual e Cielo.", "Transacao nao permitida. Houve uma falha na validacao dos dados. reveja os dados informados e tente novamente. Se o erro persistir entre em contato com a Loja Virtual.", 0),
    FALHA_GD("GD", "Transacao nao permitida", "Transacao nao permitida", "Transacao nao é possível ser processada no estabelecimento. Entre em contato com a Cielo para obter mais detalhes Transacao", 0);

    private String returnCode;
    private String definition;
    private String meaning;
    private String action;
    private int maxRetries;

    private CieloOrderReturnCode(String returnCode, String definition, String meaning, String action, int maxRetries) {
        this.returnCode = returnCode;
        this.definition = definition;
        this.meaning = meaning;
        this.action = action;
        this.maxRetries = maxRetries;
    }
}

